use_lora: false
bf16: true
batch_size: 4             # Adjust based on your GPU VRAM
grad_accumulation: 4
num_workers: 8
epochs: 1
logging_steps: 10      # Log loss every 10 steps
grad_checkpointing: true   # Enable gradient checkpointing (saves VRAM)
data_usage: 1.0        # Use a fraction of the dataset for quicker experiments (1.0 = full dataset)
# data_usage: 0.01        # for fast debug run

# # my default training args
# learning_rate: 1e-3 # 2e-4 for LLM 1e-3 for MMP (projector)
# warmup_ratio: 0.03        # Warmup ratio for learning rate scheduler
# lr_scheduler_type: "cosine"

# best online winner (InternVL4Drive) - NJU
learning_rate: 2e-5

# # best offline winner (llava1.6-lora(llama_only)) - CPS
# learning_rate: 2e-5
# warmup_ratio: 0.03             # MATCHES: First 3% of training steps
# lr_scheduler_type: "cosine"


# Control what to finetune with LoRA /QLoRA
# Options: ["language_model", "vision_model", "multi_modal_projector"]
train_modules: ["multi_modal_projector"]  
# HOW TO TRAIN THE PROJECTOR
# "lora" = Freezes weights, trains adapters on linear_1/linear_2 (Efficient)
# "full" = Unfreezes original weights (Standard LLaVA approach)
projector_mode: "full"
