import json
import re
import os

class DriveLMPostProcessor:
    def __init__(self):
        self.stats = {
            "empty_fixed": 0,
            "multiple_choice_fixed": 0,
            "yes_no_fixed": 0,
            "coordinates_fixed": 0,
            "default_cleanup_fixed": 0,
            "total_processed": 0,
            "total_fixed": 0
        }

    def ensure_dir(self, file_path):
        """Creates the directory for the given file path if it doesn't exist."""
        directory = os.path.dirname(file_path)
        if directory and not os.path.exists(directory):
            print(f"Creating directory: {directory}")
            os.makedirs(directory, exist_ok=True)

    def fix_empty(self, answer):
        """Check category: Empty, None, or strings with ONLY special characters."""
        ans_str = str(answer).strip()
        
        # 1. Check for completely empty strings or the explicit string "None"
        if not ans_str or ans_str.lower() == "none":
            return "Not answered", True
            
        # 2. Check if the string contains NO letters and NO numbers.
        # If there are no alphanumeric characters, it means it's just symbols (e.g., "-", ".", "???", "< >")
        if not re.search(r'[a-zA-Z0-9]', ans_str):
            return "Not answered", True
            
        return ans_str, False

    def fix_multiple_choice(self, question, answer):
        """Check category: Multiple choice extraction (Tag 0/Accuracy)."""
        if "Please select the correct answer" in question or "options:" in question.lower():
            clean_ans = answer.strip()
            if clean_ans in ["A", "B", "C", "D"]:
                return clean_ans, False

            # Matches "Answer is A", "A.", "(A)", etc.
            match = re.search(r'\b([A-D])\b', answer.upper())
            if match:
                return match.group(1), True
        return answer, False

    def fix_yes_no(self, question, answer):
        """Check category: Binary Yes/No extraction (Tag 0/Accuracy)."""
        q_lower = question.lower()
        if q_lower.startswith(("will ", "is ", "are ", "do ", "does ", "can ", "could ", "would ", "should ")):
            ans_clean = answer.strip().lower()
            if ans_clean.startswith("yes"):
                return "Yes", (ans_clean != "yes")
            if ans_clean.startswith("no"):
                return "No", (ans_clean != "no")
        return answer, False

    def fix_coordinates(self, answer):
        """Check category: Malformed coordinate tags (Tag 3/Match)."""
        original = answer
        # Regex to catch c1... through c999, various CAM names, and floats missing brackets
        pattern = r'<?(c\d+,[A-Z_]+,\d+(?:\.\d+)?,\d+(?:\.\d+)?)>?'
        
        def replace_match(match):
            return f"<{match.group(1)}>"
            
        fixed_answer = re.sub(pattern, replace_match, answer)
        
        # Cleanup specific severe truncation like "-8,430.8>"
        if fixed_answer == original and re.search(r'^-?\d+(?:\.\d+)?>$', fixed_answer.strip()):
            fixed_answer = "Not answered"

        return fixed_answer, (fixed_answer != original)

    def default_cleanup(self, answer):
        """Check category: General formatting and Unicode decoding."""
        original = answer
        fixed = answer.strip()
        
        # Fix literal unicode escapes generated by the model (e.g., turning literal \u00e9 string into character é)
        try:
            # We encode to ascii, then decode as unicode_escape to evaluate the literal backslashes
            if r'\u' in fixed:
                fixed = fixed.encode('ascii').decode('unicode_escape')
        except Exception:
            pass # If it fails, just keep the original string

        # Remove trailing periods from single-word answers
        if len(fixed.split()) == 1 and fixed.endswith("."):
            fixed = fixed[:-1]
        
        # Quick specific text cleanups based on your dataset
        fixed = fixed.replace("très ", "very ")
        
        return fixed, (fixed != original)

    def process_item(self, item):
        self.stats["total_processed"] += 1
        question = item.get("question", "")
        original_answer = str(item.get("answer", ""))
        
        answer = original_answer
        is_fixed = False
        
        # 1. Empty Check (Includes the new Alphanumeric check)
        ans, changed = self.fix_empty(answer)
        if changed:
            answer = ans
            self.stats["empty_fixed"] += 1
            is_fixed = True
        
        if answer != "Not answered":
            # 3. Multiple Choice
            ans, changed = self.fix_multiple_choice(question, answer)
            if changed:
                answer = ans
                self.stats["multiple_choice_fixed"] += 1
                is_fixed = True
            
            # 4. Yes/No
            ans, changed = self.fix_yes_no(question, answer)
            if changed:
                answer = ans
                self.stats["yes_no_fixed"] += 1
                is_fixed = True
            
            # 5. Coordinates
            ans, changed = self.fix_coordinates(answer)
            if changed:
                answer = ans
                self.stats["coordinates_fixed"] += 1
                is_fixed = True

        if is_fixed:
            self.stats["total_fixed"] += 1
        
        item["answer"] = answer
        return item

    def process_file(self, input_path, output_path, log_path):
        self.ensure_dir(output_path)
        self.ensure_dir(log_path)

        if not os.path.exists(input_path):
            print(f"❌ Error: Input file '{input_path}' not found.")
            return

        print(f"Loading predictions from {input_path}...")
        with open(input_path, 'r', encoding='utf-8') as f:
            try:
                data = json.load(f)
            except json.JSONDecodeError as e:
                print(f"❌ Error: Failed to decode JSON input. Details: {e}")
                return

        processed_data = [self.process_item(item) for item in data]
        
        print(f"Saving corrected predictions to {output_path}...")
        # ensure_ascii=False forces the file to write pure UTF-8 characters (like é) instead of \u00e9
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(processed_data, f, indent=4, ensure_ascii=False)
            
        self.print_stats(log_path)

    def print_stats(self, log_file_path):
        stats_text = (
            "========================================\n"
            "      DRIVELM CORRECTION STATISTICS\n"
            "========================================\n"
            f"Total VQA pairs processed: {self.stats['total_processed']}\n"
            f"Total outputs modified:    {self.stats['total_fixed']}\n"
            "----------------------------------------\n"
            "Breakdown by Category:\n"
            f"  • Empty/Invalid fixed:   {self.stats['empty_fixed']}\n"
            # f"  • General text cleanup:  {self.stats['default_cleanup_fixed']}\n"
            f"  • Multiple choice (A/B): {self.stats['multiple_choice_fixed']}\n"
            f"  • Yes/No normalization:  {self.stats['yes_no_fixed']}\n"
            f"  • Coordinate tags <>:    {self.stats['coordinates_fixed']}\n"
            "========================================\n"
        )
        print("\n" + stats_text)
        with open(log_file_path, 'w', encoding='utf-8') as f:
            f.write(stats_text)
        print(f"✅ Statistics saved to: {log_file_path}\n")


if __name__ == "__main__":
    # Specify your file paths here
    # path = "/mnt/proj1/eu-25-10/dmytro/RoadCap-Gen/output/inference/infer_llava_finetuned_on_drivelm_train0.7_gpu4_bs8_nw4_e0_pretrained_2026-03-04_01-08-44/"
    
    INPUT_FILE = "/mnt/proj1/eu-25-10/dmytro/RoadCap-Gen/output/inference/infer_llava_finetuned_on_drivelm_train1.0-alldata_gpu4_bs8_nw4_e10_ckpt580_2026-03-04_02-28-48/drivelm_pred_for_HF_test_qas_2026-03-04_02-28-48.json"
    OUTPUT_FILE = INPUT_FILE.replace(".json", "_corrected.json")
    LOG_FILE = INPUT_FILE.split(".json")[0] + "_correction_stats.txt"
    
    processor = DriveLMPostProcessor()
    processor.process_file(INPUT_FILE, OUTPUT_FILE, LOG_FILE)